### ISSUE TITLE
New Licenses

### ISSUE THREAD

**Issue by Cocaina-Ricky** [HeroesOfGaming/HeroesAltis-4.0#4]
**License Price:**
Rebel Training - 3 Million

**New Licenses:**
Advanced Rebel - 10 Million
Corporation - 3 Million
Advanced Corporation - 10 Million

**Comment by Cocaina-Ricky** [comment]
Needs to be on mission.sqm

**Comment by AmnartH** [comment]
Need to add NPC in Pygros police station (Pygros = Corp HQ) with those licenses (will add civ shops for now, making new shops soon)

**Comment by Cocaina-Ricky** [comment]
Completed by @Cocaina-Ricky.
